import { useMutation, useQuery, useQueryClient, keepPreviousData } from '@tanstack/react-query';
import {
  AlertTriangle,
  CalendarPlus,
  ChevronLeft,
  ChevronRight,
  LayoutGrid,
  List,
  Megaphone,
  Move,
  ShieldCheck,
  Trash2,
  Wand2,
} from 'lucide-react';
import { useState } from 'react';
import { PageHeader } from '@/components/layout/PageHeader';
import { Alert } from '@/components/ui/alert';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Card, CardContent } from '@/components/ui/card';
import { EmptyState } from '@/components/ui/empty-state';
import { Field } from '@/components/ui/field';
import { Input } from '@/components/ui/input';
import { NativeSelect } from '@/components/ui/native-select';
import { Skeleton } from '@/components/ui/skeleton';
import { toast } from '@/components/ui/toaster';
import { adminApi } from '@/lib/admin-api';
import { parseApiError } from '@/lib/api';
import { formatDateTime } from '@/lib/format';
import {
  addDaysIso,
  isoToDdMmYyyy,
  mondayIso,
  slotPassed,
  schedulingApi,
  todayIso,
  weekdayName,
  type Board,
  type HearingView,
} from '@/lib/scheduling-api';
import { cn } from '@/lib/utils';
import {
  AutoGenerateDialog,
  CancelHearingDialog,
  RescheduleDialog,
  RunCheckPanel,
  ScheduleHearingDialog,
} from './BoardDialogs';

const STATUS_VARIANT = {
  SCHEDULED: 'hearing',
  ADJOURNED: 'pending',
  HELD: 'decided',
  CANCELLED: 'rejected',
} as const;
const STATUS_LABEL = {
  SCHEDULED: 'Scheduled',
  ADJOURNED: 'Adjourned',
  HELD: 'Held',
  CANCELLED: 'Cancelled',
} as const;

function HearingCard({
  h,
  roomName,
  onReschedule,
  onCancel,
  dragging,
  onDragStart,
  onDragEnd,
}: {
  h: HearingView;
  roomName: string;
  onReschedule: () => void;
  onCancel: () => void;
  dragging: boolean;
  onDragStart: () => void;
  onDragEnd: () => void;
}) {
  const clash = h.conflicts.length > 0;
  return (
    <div
      draggable
      onDragStart={(e) => {
        e.dataTransfer.setData('text/plain', h.id);
        e.dataTransfer.effectAllowed = 'move';
        onDragStart();
      }}
      onDragEnd={onDragEnd}
      className={cn(
        'h-full min-w-40 cursor-grab space-y-1 rounded-md border bg-surface p-2 text-left',
        clash ? 'border-2 border-destructive bg-status-rejected-bg' : 'border-border',
        dragging && 'opacity-50',
      )}
    >
      <p className="case-number truncate text-xs font-medium text-primary" title={h.ucn}>
        {h.ucn}
      </p>
      <p className="line-clamp-2 text-sm font-semibold leading-snug" title={h.title}>
        {h.title}
      </p>
      <Badge variant={STATUS_VARIANT[h.status]}>{STATUS_LABEL[h.status]}</Badge>
      {clash && (
        <p className="flex items-start gap-1 text-xs font-semibold text-status-rejected-fg">
          <AlertTriangle className="mt-0.5 size-3.5 shrink-0" aria-hidden="true" />
          <span>{h.conflicts[0].message}</span>
        </p>
      )}
      <div className="flex gap-1 pt-1">
        <Button
          size="sm"
          variant="secondary"
          className="min-h-8 px-2 text-xs"
          onClick={onReschedule}
          aria-label={`${clash ? 'Resolve conflict for' : 'Reschedule'} ${h.ucn}, ${h.startTime} in ${roomName}`}
        >
          <Move aria-hidden="true" /> {clash ? 'Resolve' : 'Reschedule'}
        </Button>
        <Button
          size="sm"
          variant="ghost"
          className="min-h-8 px-2"
          onClick={onCancel}
          aria-label={`Cancel hearing ${h.ucn}`}
        >
          <Trash2 aria-hidden="true" />
        </Button>
      </div>
    </div>
  );
}

/** UC-3.1 / 3.2 / 3.3: Master Bench Allocation and Scheduling Board. */
export default function BoardPage() {
  const queryClient = useQueryClient();
  const [courtChoice, setCourtId] = useState('');
  const [date, setDate] = useState(todayIso());
  const [view, setView] = useState<'grid' | 'agenda'>(() =>
    typeof window !== 'undefined' && window.innerWidth < 768 ? 'agenda' : 'grid',
  );
  const [scheduling, setScheduling] = useState<{ courtroomId?: string; slot?: number } | null>(
    null,
  );
  const [moving, setMoving] = useState<HearingView | null>(null);
  const [cancelling, setCancelling] = useState<HearingView | null>(null);
  const [auto, setAuto] = useState(false);
  const [dragId, setDragId] = useState<string | null>(null);
  const [dropError, setDropError] = useState<string | null>(null);
  const [checkResult, setCheckResult] = useState<Awaited<
    ReturnType<typeof schedulingApi.runCheck>
  > | null>(null);

  const courts = useQuery({ queryKey: ['admin', 'courts'], queryFn: adminApi.courts });
  const courtId =
    courtChoice || (courts.data?.find((c) => c.isActive) ?? courts.data?.[0])?.id || '';

  const board = useQuery({
    queryKey: ['scheduling', 'board', courtId, date],
    queryFn: () => schedulingApi.board(courtId, date),
    enabled: Boolean(courtId),
    placeholderData: keepPreviousData,
    refetchInterval: 30_000,
  });
  const week = useQuery({
    queryKey: ['scheduling', 'week', courtId, mondayIso(date)],
    queryFn: () => schedulingApi.week(courtId, mondayIso(date)),
    enabled: Boolean(courtId),
    placeholderData: keepPreviousData,
  });

  const refresh = () => queryClient.invalidateQueries({ queryKey: ['scheduling'] });
  const b = board.data as Board | undefined;
  const past = date < todayIso();
  const bookable = Boolean(b?.isWorkingDay) && !past;

  const runCheck = useMutation({
    mutationFn: () => schedulingApi.runCheck(courtId, date),
    onSuccess: (res) => {
      setCheckResult(res);
      if (res.valid) toast.success(res.message);
    },
    onError: (e) => toast.error(parseApiError(e).message),
  });

  const publish = useMutation({
    mutationFn: () => schedulingApi.publish(courtId, date),
    onSuccess: async (res) => {
      toast.success(res.message);
      await refresh();
    },
    onError: (e) => toast.error(parseApiError(e).message),
  });

  const drop = useMutation({
    mutationFn: (v: { hearing: HearingView; courtroomId: string; slot: number }) =>
      schedulingApi.reschedule(v.hearing.id, {
        date,
        slot: v.slot,
        courtroomId: v.courtroomId,
        resolveConflict: v.hearing.conflicts.length > 0,
      }),
    onSuccess: async (res) => {
      setDropError(null);
      toast.success(res.message);
      await refresh();
    },
    onError: (e) => {
      const body = parseApiError(e);
      const message =
        (body.details as { message?: string }[] | undefined)?.[0]?.message ?? body.message;
      setDropError(message);
      toast.error(message);
    },
  });

  function findHearing(id: string): HearingView | null {
    for (const r of b?.courtrooms ?? []) {
      for (const c of r.cells) if (c.hearing?.id === id) return c.hearing;
    }
    return null;
  }

  function onDropCell(courtroomId: string, slot: number, e: React.DragEvent) {
    e.preventDefault();
    const id = e.dataTransfer.getData('text/plain');
    setDragId(null);
    const hearing = findHearing(id);
    if (!hearing) return;
    if (hearing.courtroom?.id === courtroomId && hearing.slot === slot) return;
    drop.mutate({ hearing, courtroomId, slot });
  }

  const statusForPublish = !b
    ? null
    : !b.isWorkingDay
      ? 'Not a working day.'
      : b.conflictCount > 0
        ? 'Resolve all scheduling conflicts before publishing.'
        : b.hearingCount === 0
          ? 'There are no hearings to publish.'
          : null;

  return (
    <>
      <PageHeader
        title="Master Bench Allocation and Scheduling Board"
        description="Every courtroom and judge across the day, with anti-clash checks. Drag a hearing onto a free slot to move it."
        crumbs={[{ label: 'Dashboard', to: '/admin' }, { label: 'Bench Scheduling' }]}
      />

      <Card className="mb-4">
        <CardContent className="space-y-4">
          <div className="grid gap-3 md:grid-cols-[minmax(0,2fr)_auto] md:items-end">
            <Field label="Court">
              {(p) => (
                <NativeSelect value={courtId} onChange={(e) => setCourtId(e.target.value)} {...p}>
                  {courts.data?.map((c) => (
                    <option key={c.id} value={c.id}>
                      {c.name}
                    </option>
                  ))}
                </NativeSelect>
              )}
            </Field>
            <div className="flex items-end gap-2">
              <Button
                variant="secondary"
                size="icon"
                onClick={() => setDate(addDaysIso(date, -1))}
                aria-label="Previous day"
              >
                <ChevronLeft aria-hidden="true" />
              </Button>
              <div className="flex-1">
                <Field label="Date">
                  {(p) => (
                    <Input
                      type="date"
                      value={date}
                      onChange={(e) => e.target.value && setDate(e.target.value)}
                      {...p}
                    />
                  )}
                </Field>
              </div>
              <Button
                variant="secondary"
                size="icon"
                onClick={() => setDate(addDaysIso(date, 1))}
                aria-label="Next day"
              >
                <ChevronRight aria-hidden="true" />
              </Button>
              <Button variant="ghost" onClick={() => setDate(todayIso())}>
                Today
              </Button>
            </div>
          </div>

          <div role="group" aria-label="Week" className="grid grid-cols-5 gap-2">
            {week.data?.days.map((d) => (
              <button
                key={d.date}
                type="button"
                onClick={() => setDate(d.date)}
                aria-pressed={d.date === date}
                aria-label={`${weekdayName(d.date)} ${isoToDdMmYyyy(d.date)}, ${d.total} hearings${d.conflicts ? `, ${d.conflicts} in conflict` : ''}`}
                className={cn(
                  'min-h-14 rounded-md border px-2 py-1 text-left text-sm',
                  d.date === date
                    ? 'border-primary bg-primary-soft'
                    : 'border-border bg-surface hover:bg-primary-soft',
                )}
              >
                <span className="block font-semibold">{weekdayName(d.date).slice(0, 3)}</span>
                <span className="block text-xs text-text-muted">
                  {d.date.slice(8, 10)}-{d.date.slice(5, 7)}
                </span>
                <span className="block text-xs">
                  {d.total} hearing{d.total === 1 ? '' : 's'}
                  {d.conflicts > 0 && (
                    <span className="ml-1 font-bold text-destructive">· {d.conflicts} clash</span>
                  )}
                </span>
              </button>
            ))}
          </div>

          <div className="flex flex-wrap items-center gap-2">
            <Button onClick={() => setScheduling({})} disabled={!b || !bookable}>
              <CalendarPlus aria-hidden="true" /> Schedule hearing
            </Button>
            <Button
              variant="secondary"
              onClick={() => runCheck.mutate()}
              loading={runCheck.isPending}
              disabled={!courtId}
            >
              <ShieldCheck aria-hidden="true" /> Run Anti-Clash Check
            </Button>
            <Button variant="secondary" onClick={() => setAuto(true)} disabled={!b || !bookable}>
              <Wand2 aria-hidden="true" /> Auto-generate schedule
            </Button>
            <span title={statusForPublish ?? undefined}>
              <Button
                variant="secondary"
                onClick={() => publish.mutate()}
                loading={publish.isPending}
                disabled={Boolean(statusForPublish)}
                aria-describedby="publish-hint"
              >
                <Megaphone aria-hidden="true" /> Publish Cause List
              </Button>
            </span>
            <span id="publish-hint" className="text-sm text-text-muted">
              {b?.causeList?.status === 'PUBLISHED'
                ? `Published ${formatDateTime(b.causeList.publishedAt)}`
                : (statusForPublish ?? 'Not published yet')}
            </span>
            <div role="group" aria-label="View" className="ml-auto flex gap-1">
              <Button
                variant={view === 'grid' ? 'primary' : 'secondary'}
                size="sm"
                onClick={() => setView('grid')}
                aria-pressed={view === 'grid'}
              >
                <LayoutGrid aria-hidden="true" /> Grid
              </Button>
              <Button
                variant={view === 'agenda' ? 'primary' : 'secondary'}
                size="sm"
                onClick={() => setView('agenda')}
                aria-pressed={view === 'agenda'}
              >
                <List aria-hidden="true" /> Agenda
              </Button>
            </div>
          </div>
        </CardContent>
      </Card>

      {checkResult && (
        <div className="mb-4">
          <RunCheckPanel
            result={checkResult}
            onResolve={(h) => {
              const full = findHearing(h.id);
              if (full) setMoving(full);
            }}
          />
        </div>
      )}
      {dropError && (
        <Alert variant="error" className="mb-4" title="Hearing not moved">
          {dropError}
        </Alert>
      )}
      {board.isError && <Alert variant="error">{parseApiError(board.error).message}</Alert>}

      {!b ? (
        <div role="status" aria-label="Loading board" className="space-y-3">
          <Skeleton className="h-16" />
          <Skeleton className="h-64" />
          <span className="sr-only">Loading…</span>
        </div>
      ) : (
        <>
          <div
            className="mb-3 flex flex-wrap items-center gap-x-5 gap-y-1 text-sm"
            aria-label="Legend"
          >
            <span className="font-semibold">
              {b.weekday} {isoToDdMmYyyy(b.date)}
            </span>
            <span className="inline-flex items-center gap-1.5">
              <span
                className="size-3 rounded-sm border border-border bg-surface"
                aria-hidden="true"
              />{' '}
              Booked
            </span>
            <span className="inline-flex items-center gap-1.5">
              <span
                className="size-3 rounded-sm border-2 border-dashed border-primary"
                aria-hidden="true"
              />{' '}
              Free slot
            </span>
            <span className="inline-flex items-center gap-1.5">
              <AlertTriangle className="size-3.5 text-destructive" aria-hidden="true" />
              <span
                className="size-3 rounded-sm border-2 border-destructive bg-status-rejected-bg"
                aria-hidden="true"
              />{' '}
              Conflict ({b.conflictCount})
            </span>
          </div>

          {!b.isWorkingDay ? (
            <Card>
              <EmptyState
                icon={CalendarPlus}
                title="Not a working day"
                description="Courts sit Monday to Friday. Choose a weekday to schedule hearings."
              />
            </Card>
          ) : b.courtrooms.length === 0 ? (
            <Card>
              <EmptyState
                icon={LayoutGrid}
                title="No courtrooms in this court"
                description="Add courtrooms under Courts & Benches."
              />
            </Card>
          ) : view === 'grid' ? (
            <div className="w-full overflow-x-auto rounded-lg border border-border bg-surface">
              <table
                role="grid"
                aria-label={`Hearing schedule for ${b.court.name} on ${isoToDdMmYyyy(b.date)}`}
                className="w-full border-collapse text-sm"
              >
                <thead className="bg-primary-soft">
                  <tr>
                    <th
                      scope="col"
                      className="sticky left-0 z-10 min-w-44 bg-primary-soft px-3 py-2 text-left"
                    >
                      Courtroom and judge
                    </th>
                    {b.slots.map((s) => (
                      <th
                        key={s.slot}
                        scope="col"
                        className="min-w-44 whitespace-nowrap px-3 py-2 text-left"
                      >
                        {s.start}–{s.end}
                      </th>
                    ))}
                  </tr>
                </thead>
                <tbody>
                  {b.courtrooms.map((room) => (
                    <tr key={room.id} className="border-t border-border align-top">
                      <th
                        scope="row"
                        className="sticky left-0 z-10 bg-surface px-3 py-2 text-left font-normal"
                      >
                        <span className="block font-semibold">{room.name}</span>
                        {room.judges.map((j) => (
                          <span key={j.id} className="block text-xs text-text-muted">
                            {j.name} · {j.used}/{j.total} slots
                          </span>
                        ))}
                        {room.judges.length === 0 && (
                          <span className="text-xs text-text-muted">No judge assigned</span>
                        )}
                      </th>
                      {room.cells.map((cell) => {
                        const s = b.slots.find((x) => x.slot === cell.slot)!;
                        return (
                          <td
                            key={cell.slot}
                            role="gridcell"
                            className="p-1.5"
                            onDragOver={(e) => !cell.hearing && bookable && e.preventDefault()}
                            onDrop={(e) =>
                              !cell.hearing && bookable && onDropCell(room.id, cell.slot, e)
                            }
                          >
                            {cell.hearing ? (
                              <HearingCard
                                h={cell.hearing}
                                roomName={room.name}
                                dragging={dragId === cell.hearing.id}
                                onDragStart={() => setDragId(cell.hearing!.id)}
                                onDragEnd={() => setDragId(null)}
                                onReschedule={() => setMoving(cell.hearing)}
                                onCancel={() => setCancelling(cell.hearing)}
                              />
                            ) : (
                              <button
                                type="button"
                                disabled={!bookable || slotPassed(b.date, s.start)}
                                onClick={() =>
                                  setScheduling({ courtroomId: room.id, slot: cell.slot })
                                }
                                aria-label={`Free slot ${s.start} in ${room.name}. Schedule a hearing`}
                                className="flex min-h-20 w-full items-center justify-center rounded-md border-2 border-dashed border-border text-xs font-medium text-text-muted hover:border-primary hover:bg-primary-soft hover:text-primary disabled:cursor-not-allowed disabled:opacity-50"
                              >
                                Free
                              </button>
                            )}
                          </td>
                        );
                      })}
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          ) : (
            <div className="space-y-4">
              {b.courtrooms.map((room) => {
                const booked = room.cells.filter((c) => c.hearing);
                return (
                  <Card key={room.id}>
                    <CardContent className="space-y-3">
                      <div>
                        <h2 className="text-lg font-bold">{room.name}</h2>
                        <p className="text-sm text-text-muted">
                          {room.judges.map((j) => `${j.name} (${j.used}/${j.total})`).join(', ') ||
                            'No judge assigned'}
                        </p>
                      </div>
                      <ul className="space-y-2">
                        {room.cells.map((cell) => {
                          const s = b.slots.find((x) => x.slot === cell.slot)!;
                          return (
                            <li
                              key={cell.slot}
                              className="grid grid-cols-[4.5rem_1fr] items-start gap-3"
                            >
                              <span className="pt-2 font-mono text-sm">{s.start}</span>
                              {cell.hearing ? (
                                <HearingCard
                                  h={cell.hearing}
                                  roomName={room.name}
                                  dragging={false}
                                  onDragStart={() => undefined}
                                  onDragEnd={() => undefined}
                                  onReschedule={() => setMoving(cell.hearing)}
                                  onCancel={() => setCancelling(cell.hearing)}
                                />
                              ) : (
                                <Button
                                  variant="secondary"
                                  size="sm"
                                  disabled={!bookable || slotPassed(b.date, s.start)}
                                  className="justify-start"
                                  onClick={() =>
                                    setScheduling({ courtroomId: room.id, slot: cell.slot })
                                  }
                                  aria-label={`Free slot ${s.start} in ${room.name}. Schedule a hearing`}
                                >
                                  Free · schedule a hearing
                                </Button>
                              )}
                            </li>
                          );
                        })}
                      </ul>
                      {booked.length === 0 && (
                        <p className="text-sm text-text-muted">No hearings booked.</p>
                      )}
                    </CardContent>
                  </Card>
                );
              })}
            </div>
          )}

          {scheduling && (
            <ScheduleHearingDialog
              board={b}
              initial={{ courtroomId: scheduling.courtroomId, date, slot: scheduling.slot }}
              onClose={() => setScheduling(null)}
            />
          )}
          {moving && (
            <RescheduleDialog board={b} hearing={moving} onClose={() => setMoving(null)} />
          )}
          {cancelling && (
            <CancelHearingDialog hearing={cancelling} onClose={() => setCancelling(null)} />
          )}
          {auto && <AutoGenerateDialog board={b} onClose={() => setAuto(false)} />}
        </>
      )}
    </>
  );
}
