import ExcelJS from 'exceljs';
import { createWriteStream } from 'node:fs';
import PDFDocument from 'pdfkit';
import { Bucket, PerformanceReport } from './performance.service';

const GREEN = '#01411C';
const INK = '#1A1A1A';
const MUTED = '#4A524C';

export interface AuditExportRow {
  eventId: string;
  time: string;
  userHash: string;
  actorEmail: string;
  role: string;
  action: string;
  entity: string;
  entityId: string;
  success: string;
  eventHash: string;
}

export type ReportData =
  | { kind: 'PERFORMANCE'; report: PerformanceReport }
  | { kind: 'AUDIT_TRAIL'; rows: AuditExportRow[]; filters: Record<string, unknown> };

/** Everything the waterstamp (PDF watermark and footer, Excel Verification sheet) needs. */
export interface WaterStamp {
  code: string;
  seal: string;
  generatedAt: string; // already formatted DD-MM-YYYY HH:mm:ss
  generatedBy: string;
  dataSha256: string;
  params: Record<string, unknown>;
  kindLabel: string;
}

export const KIND_LABEL = {
  PERFORMANCE: 'Judicial Performance Report',
  AUDIT_TRAIL: 'Audit Trail',
} as const;

const fmtNum = (n: number | null, suffix = '') => (n === null ? 'n/a' : `${n}${suffix}`);

// ---------------------------------------------------------------------------------------------- PDF

type Doc = PDFKit.PDFDocument;

function stamp(doc: Doc, s: WaterStamp) {
  const { width: w, height: h } = doc.page;
  const x = doc.x;
  const y = doc.y;
  // Diagonal light watermark.
  doc.save();
  doc.rotate(-35, { origin: [w / 2, h / 2] });
  doc.fillColor(GREEN).fillOpacity(0.07).font('Helvetica-Bold').fontSize(30);
  doc.text(`DigitalAdaalat - Verified ${s.code}`, w / 2 - 340, h / 2 - 15, {
    width: 680,
    align: 'center',
    lineBreak: false,
  });
  doc.restore();
  // Footer: written inside the bottom margin, so margins are lifted for a moment.
  const bottom = doc.page.margins.bottom;
  doc.page.margins.bottom = 0;
  doc.fillOpacity(1).fillColor(MUTED).font('Helvetica').fontSize(7);
  doc.text(
    `Verified ${s.code}  |  Seal ${s.seal.slice(0, 16)}  |  Generated by DigitalAdaalat on ${s.generatedAt}`,
    doc.page.margins.left,
    h - 30,
    {
      width: w - doc.page.margins.left - doc.page.margins.right,
      align: 'center',
      lineBreak: false,
    },
  );
  doc.page.margins.bottom = bottom;
  doc.x = x;
  doc.y = y;
}

function heading(doc: Doc, text: string) {
  doc.moveDown(0.8);
  doc.fillColor(GREEN).font('Helvetica-Bold').fontSize(12).text(text);
  doc.moveDown(0.3);
}

function table(doc: Doc, headers: string[], rows: string[][], widths: number[], size = 8.5) {
  const left = doc.page.margins.left;
  const draw = (cells: string[], bold: boolean) => {
    const rowH = size + 7;
    if (doc.y + rowH > doc.page.height - doc.page.margins.bottom - 8) doc.addPage();
    const y = doc.y;
    if (bold)
      doc
        .rect(
          left,
          y - 2,
          widths.reduce((a, b) => a + b, 0),
          rowH,
        )
        .fill('#E8F0EA');
    doc
      .fillColor(INK)
      .font(bold ? 'Helvetica-Bold' : 'Helvetica')
      .fontSize(size);
    let x = left;
    cells.forEach((c, i) => {
      doc.text(c, x + 3, y + 1, {
        width: widths[i] - 6,
        height: rowH - 2,
        ellipsis: true,
        lineBreak: false,
      });
      x += widths[i];
    });
    doc.y = y + rowH;
    doc.x = left;
  };
  draw(headers, true);
  for (const r of rows) draw(r, false);
}

function bucketRows(b: Bucket[]) {
  return b.map((x) => [
    x.label,
    String(x.filed),
    String(x.decided),
    String(x.pending),
    fmtNum(x.disposalRatePercent, '%'),
    fmtNum(x.avgTrialDays),
  ]);
}

export async function renderPdf(path: string, data: ReportData, s: WaterStamp): Promise<void> {
  const audit = data.kind === 'AUDIT_TRAIL';
  const doc = new PDFDocument({
    size: 'A4',
    layout: audit ? 'landscape' : 'portrait',
    margins: { top: 50, left: 40, right: 40, bottom: 50 },
    bufferPages: false,
    info: {
      Title: `${s.kindLabel} ${s.code}`,
      Author: 'DigitalAdaalat',
      Subject: `Verified ${s.code}`,
    },
  });
  const out = createWriteStream(path);
  const finished = new Promise<void>((resolve, reject) => {
    out.on('finish', resolve);
    out.on('error', reject);
    doc.on('error', reject);
  });
  doc.pipe(out);
  doc.on('pageAdded', () => stamp(doc, s));
  stamp(doc, s);

  doc.fillColor(GREEN).font('Helvetica-Bold').fontSize(18).text('DigitalAdaalat');
  doc
    .fillColor(MUTED)
    .font('Helvetica')
    .fontSize(9)
    .text('Judicial ERP, Islamic Republic of Pakistan');
  doc.moveDown(0.4);
  doc
    .moveTo(doc.page.margins.left, doc.y)
    .lineTo(doc.page.width - doc.page.margins.right, doc.y)
    .strokeColor(GREEN)
    .lineWidth(1.5)
    .stroke();
  doc.moveDown(0.8);
  doc.fillColor(INK).font('Helvetica-Bold').fontSize(15).text(s.kindLabel);
  doc
    .fillColor(MUTED)
    .font('Helvetica')
    .fontSize(9)
    .text(`Report ${s.code}  |  Generated ${s.generatedAt}  |  By ${s.generatedBy}`);

  if (data.kind === 'PERFORMANCE') {
    const r = data.report;
    const p = r.params;
    doc.text(
      `Period: ${p.periodLabel}  |  Category: ${p.caseType ?? 'All'}  |  Judge bench: ${p.judgeLabel ?? 'All'}  |  Court: ${p.courtLabel ?? 'All'}`,
    );
    heading(doc, 'Overview');
    table(
      doc,
      ['Measure', 'Value'],
      [
        ['Cases filed in the period', String(r.summary.filed)],
        ['Cases decided in the period', String(r.summary.decided)],
        ['Still pending at the end of the period', String(r.summary.pending)],
        ['Disposal rate (decided / filed)', fmtNum(r.summary.disposalRatePercent, '%')],
        ['Average trial duration (days)', fmtNum(r.summary.avgTrialDays)],
        ['Average hearings per decided case', fmtNum(r.summary.avgHearingsPerDecided)],
      ],
      [300, 215],
      9.5,
    );
    heading(doc, 'Month by month');
    table(
      doc,
      ['Month', 'Filed', 'Decided'],
      r.monthly.map((m) => [m.label, String(m.filed), String(m.decided)]),
      [200, 100, 100],
    );
    const widths = [175, 55, 60, 60, 80, 85];
    const head = ['', 'Filed', 'Decided', 'Pending', 'Disposal rate', 'Avg days'];
    heading(doc, 'By case category');
    table(doc, ['Category', ...head.slice(1)], bucketRows(r.byCaseType), widths);
    heading(doc, 'By judge bench');
    table(doc, ['Judge', ...head.slice(1)], bucketRows(r.byJudge), widths);
    heading(doc, 'By court');
    table(doc, ['Court', ...head.slice(1)], bucketRows(r.byCourt), widths);
  } else {
    doc.text(`Rows: ${data.rows.length}  |  Filters: ${JSON.stringify(data.filters)}`);
    doc.moveDown(0.6);
    const widths = [62, 100, 70, 150, 190, 130, 40];
    const headers = ['Event ID', 'Time', 'User hash', 'Actor', 'Action', 'Entity', 'OK'];
    headerRow(doc, headers, widths);
    // Rows are drawn one by one; the header row is repeated on every new page.
    for (const r of data.rows) {
      const cells = [
        r.eventId,
        r.time,
        r.userHash,
        r.actorEmail,
        r.action,
        `${r.entity}`,
        r.success,
      ];
      rowOnly(doc, cells, widths, headers);
    }
  }

  doc.end();
  await finished;
}

function rowOnly(doc: Doc, cells: string[], widths: number[], headers: string[]) {
  const size = 7.5;
  const rowH = size + 6;
  if (doc.y + rowH > doc.page.height - doc.page.margins.bottom - 8) {
    doc.addPage();
    headerRow(doc, headers, widths);
  }
  const y = doc.y;
  doc.fillColor(INK).font('Helvetica').fontSize(size);
  let x = doc.page.margins.left;
  cells.forEach((c, i) => {
    doc.text(c, x + 2, y + 1, {
      width: widths[i] - 4,
      height: rowH - 2,
      ellipsis: true,
      lineBreak: false,
    });
    x += widths[i];
  });
  doc.y = y + rowH;
  doc.x = doc.page.margins.left;
}

function headerRow(doc: Doc, headers: string[], widths: number[]) {
  const size = 8;
  const y = doc.y;
  doc
    .rect(
      doc.page.margins.left,
      y - 2,
      widths.reduce((a, b) => a + b, 0),
      size + 7,
    )
    .fill('#E8F0EA');
  doc.fillColor(INK).font('Helvetica-Bold').fontSize(size);
  let x = doc.page.margins.left;
  headers.forEach((c, i) => {
    doc.text(c, x + 2, y + 1, { width: widths[i] - 4, lineBreak: false });
    x += widths[i];
  });
  doc.y = y + size + 7;
  doc.x = doc.page.margins.left;
}

// ---------------------------------------------------------------------------------------------- Excel

function sheetOf(
  wb: ExcelJS.Workbook,
  name: string,
  headers: string[],
  rows: (string | number | null)[][],
  widths: number[],
) {
  const ws = wb.addWorksheet(name);
  ws.columns = headers.map((h, i) => ({ header: h, key: `c${i}`, width: widths[i] ?? 18 }));
  const head = ws.getRow(1);
  head.font = { bold: true, color: { argb: 'FFFFFFFF' } };
  head.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FF01411C' } };
  for (const r of rows) ws.addRow(r);
  ws.views = [{ state: 'frozen', ySplit: 1 }];
  return ws;
}

export async function renderExcel(path: string, data: ReportData, s: WaterStamp): Promise<void> {
  const wb = new ExcelJS.Workbook();
  wb.creator = 'DigitalAdaalat';
  wb.created = new Date();
  if (data.kind === 'PERFORMANCE') {
    const r = data.report;
    sheetOf(
      wb,
      'Overview',
      ['Measure', 'Value'],
      [
        ['Period', r.params.periodLabel],
        ['Case category', r.params.caseType ?? 'All'],
        ['Judge bench', r.params.judgeLabel ?? 'All'],
        ['Court', r.params.courtLabel ?? 'All'],
        ['Cases filed', r.summary.filed],
        ['Cases decided', r.summary.decided],
        ['Pending at the end of the period', r.summary.pending],
        ['Disposal rate (%)', r.summary.disposalRatePercent],
        ['Average trial duration (days)', r.summary.avgTrialDays],
        ['Average hearings per decided case', r.summary.avgHearingsPerDecided],
      ],
      [40, 30],
    );
    sheetOf(
      wb,
      'Monthly',
      ['Month', 'Filed', 'Decided'],
      r.monthly.map((m) => [m.label, m.filed, m.decided]),
      [18, 12, 12],
    );
    const head = ['Filed', 'Decided', 'Pending', 'Disposal rate (%)', 'Average trial days'];
    const body = (b: Bucket[]) =>
      b.map((x) => [x.label, x.filed, x.decided, x.pending, x.disposalRatePercent, x.avgTrialDays]);
    sheetOf(wb, 'By category', ['Category', ...head], body(r.byCaseType), [28, 10, 10, 10, 18, 20]);
    sheetOf(wb, 'By judge', ['Judge', ...head], body(r.byJudge), [28, 10, 10, 10, 18, 20]);
    sheetOf(wb, 'By court', ['Court', ...head], body(r.byCourt), [34, 10, 10, 10, 18, 20]);
  } else {
    sheetOf(
      wb,
      'Audit trail',
      [
        'Event ID',
        'Time (Pakistan)',
        'User hash',
        'Actor',
        'Role',
        'Action',
        'Entity',
        'Entity ID',
        'Success',
        'Event hash',
      ],
      data.rows.map((r) => [
        r.eventId,
        r.time,
        r.userHash,
        r.actorEmail,
        r.role,
        r.action,
        r.entity,
        r.entityId,
        r.success,
        r.eventHash,
      ]),
      [14, 22, 16, 30, 14, 34, 18, 38, 10, 66],
    );
  }
  sheetOf(
    wb,
    'Verification',
    ['Item', 'Value'],
    [
      ['Verification code', s.code],
      ['Report', s.kindLabel],
      ['Parameters', JSON.stringify(s.params)],
      ['Generated at (Pakistan)', s.generatedAt],
      ['Generated by', `DigitalAdaalat Judicial ERP, account ${s.generatedBy}`],
      ['SHA-256 of the data rows', s.dataSha256],
      ['Seal (HMAC-SHA256)', s.seal],
      [
        'Note',
        'Verify this file in DigitalAdaalat under Report history. Any edit to this file changes its hash.',
      ],
    ],
    [30, 110],
  );
  await wb.xlsx.writeFile(path);
}
