import {
  BadRequestException,
  ConflictException,
  Injectable,
  NotFoundException,
} from '@nestjs/common';
import { AuditAction, AuditService } from '../audit/audit.service';
import { AuthUser } from '../common/decorators';
import { Messages } from '../common/messages';
import { CaseEventType, CaseStatus, Prisma } from '../generated/prisma/client';
import { PrismaService } from '../prisma/prisma.service';
import { SettingsService } from '../settings/settings.service';
import { fullName, RequestMeta } from '../admin/constants';
import {
  AutoGenerateDto,
  CancelHearingDto,
  CheckDto,
  CreateHearingDto,
  PublishDto,
  RescheduleDto,
} from './scheduling.dto';
import {
  CLEAR_MESSAGE,
  Conflict,
  Db,
  lawyerNamesOf,
  ScanHearing,
  scanInclude,
  SchedulingEngine,
} from './scheduling.engine';
import {
  addDays,
  assertBookable,
  buildSlots,
  ddmmyyyy,
  dayLockKey,
  isoDate,
  isWorkingDay,
  mondayOf,
  requireDate,
  Slot,
  todayUtc,
  weekdayOf,
} from './slots';

const SCHEDULABLE: CaseStatus[] = ['ALLOCATED', 'PENDING', 'HEARING_FIXED'];
export const PUBLISH_BLOCKED_MESSAGE = 'Resolve all scheduling conflicts before publishing.';

const UNIQUE_MESSAGE =
  'Scheduling Conflict: this slot was just booked by someone else. Choose another slot.';

export function hearingView(h: ScanHearing, slots: Slot[], conflicts: Conflict[] = []) {
  const slot = slots.find((s) => s.slot === h.timeSlot);
  return {
    id: h.id,
    caseId: h.caseId,
    ucn: h.case.ucn,
    title: h.case.title,
    date: isoDate(h.date),
    weekday: weekdayOf(h.date),
    slot: h.timeSlot,
    startTime: h.startTime ?? slot?.start ?? null,
    endTime: slot?.end ?? null,
    status: h.status,
    purpose: h.purpose,
    courtroom: h.courtroom ? { id: h.courtroom.id, name: h.courtroom.name } : null,
    judge: { id: h.judge.id, name: fullName(h.judge) },
    lawyers: lawyerNamesOf(h),
    conflicts,
  };
}

function conflictError(conflicts: Conflict[]) {
  return new ConflictException({
    code: 'SCHEDULING_CONFLICT',
    message: conflicts[0].message,
    details: conflicts,
  });
}

function bad(field: string, text: string) {
  return new BadRequestException({
    code: 'VALIDATION_ERROR',
    message: Messages.INVALID_FIELDS,
    details: [{ field, messages: [text] }],
  });
}

/** Hearings, anti-clash scheduling and cause lists (UC-3.1 to UC-3.3). */
@Injectable()
export class SchedulingService {
  constructor(
    private readonly prisma: PrismaService,
    private readonly engine: SchedulingEngine,
    private readonly audit: AuditService,
    private readonly settings: SettingsService,
  ) {}

  // ------------------------------------------------------------------ helpers

  /** One advisory lock per calendar day, taken in sorted order so two writers cannot deadlock. */
  private async lock(tx: Db, dates: Date[]) {
    const keys = [...new Set(dates.map(dayLockKey))].sort((a, b) => a - b);
    for (const key of keys)
      await tx.$queryRaw`SELECT 1 AS locked FROM (SELECT pg_advisory_xact_lock(${key}::bigint)) AS l`;
  }

  private async loadCase(db: Db, caseId: string) {
    const c = await db.case.findUnique({
      where: { id: caseId },
      select: {
        id: true,
        ucn: true,
        title: true,
        status: true,
        courtId: true,
        judgeId: true,
        filedById: true,
        parties: { select: { lawyerId: true, lawyer: { select: { userId: true } } } },
      },
    });
    if (!c) throw new NotFoundException(Messages.NOT_FOUND);
    return {
      ...c,
      lawyerIds: [
        ...new Set(c.parties.map((p) => p.lawyerId).filter((x): x is string => Boolean(x))),
      ],
      audience: [
        ...new Set([c.filedById, ...c.parties.flatMap((p) => (p.lawyer ? [p.lawyer.userId] : []))]),
      ],
    };
  }

  private async assertTargets(
    db: Db,
    c: { courtId: string | null },
    courtroomId: string,
    judgeId: string,
  ) {
    const room = await db.courtroom.findFirst({
      where: { id: courtroomId, courtId: c.courtId ?? '', isActive: true },
      select: { id: true },
    });
    if (!room) throw bad('courtroomId', 'Choose an active courtroom of the case’s court.');
    const judge = await db.user.findFirst({
      where: { id: judgeId, role: 'JUDGE', status: 'ACTIVE', courtId: c.courtId ?? '' },
      select: { id: true },
    });
    if (!judge) throw bad('judgeId', 'Choose an active judge of the case’s court.');
  }

  private async notify(db: Db, userIds: string[], type: string, title: string, body: string) {
    if (userIds.length === 0) return;
    const now = new Date();
    await db.notification.createMany({
      data: userIds.map((userId) => ({ userId, type, title, body, sentAt: now })),
    });
  }

  private async audit_(
    db: Db,
    actor: AuthUser,
    action: string,
    entity: string,
    entityId: string,
    metadata: Prisma.InputJsonValue,
    meta: RequestMeta,
  ) {
    await this.audit.logWithin(db, {
      action,
      actorId: actor.id,
      actorRole: actor.role,
      entity,
      entityId,
      metadata,
      ...meta,
    });
  }

  private mapUnique(error: unknown): unknown {
    if (error instanceof Prisma.PrismaClientKnownRequestError && error.code === 'P2002') {
      return conflictError([{ type: 'COURTROOM', message: UNIQUE_MESSAGE }]);
    }
    return error;
  }

  private async hearingFull(db: Db, id: string) {
    return db.hearing.findUniqueOrThrow({ where: { id }, include: scanInclude });
  }

  /** Rebuilds the entries of an already published list (hearing created, moved or cancelled that day). */
  async syncCauseList(db: Db, courtId: string | null | undefined, date: Date) {
    if (!courtId) return;
    const list = await db.causeList.findUnique({ where: { courtId_date: { courtId, date } } });
    if (!list || list.status !== 'PUBLISHED') return;
    await this.rebuildEntries(db, list.id, courtId, date);
  }

  private async rebuildEntries(db: Db, causeListId: string, courtId: string, date: Date) {
    const hearings = await db.hearing.findMany({
      where: { date, status: { not: 'CANCELLED' }, courtroom: { courtId } },
      orderBy: [{ courtroom: { name: 'asc' } }, { timeSlot: 'asc' }, { id: 'asc' }],
      select: { id: true },
    });
    await db.causeListEntry.deleteMany({ where: { causeListId } });
    if (hearings.length > 0) {
      await db.causeListEntry.createMany({
        data: hearings.map((h, i) => ({ causeListId, hearingId: h.id, serialNo: i + 1 })),
      });
    }
    return hearings.length;
  }

  // ------------------------------------------------------------------ check

  /** Dry run: UC-3.2 "Execute Automated Anti-Clash Check" for one candidate slot. */
  async check(dto: CheckDto) {
    const date = requireDate(dto.date);
    const slots = buildSlots(await this.settings.schedulePolicy());
    assertBookable(date, dto.slot, slots);
    const c = await this.loadCase(this.prisma, dto.caseId);
    const judgeId = dto.judgeId ?? c.judgeId;
    if (!judgeId) throw bad('judgeId', 'This case has no judge yet. Allocate it first.');
    await this.assertTargets(this.prisma, c, dto.courtroomId, judgeId);
    const conflicts = await this.engine.findConflicts(this.prisma, {
      courtroomId: dto.courtroomId,
      judgeId,
      lawyerIds: c.lawyerIds,
      date,
      slot: dto.slot,
      excludeHearingId: dto.hearingId,
    });
    return conflicts.length === 0
      ? { valid: true, label: 'Clear/Valid', message: CLEAR_MESSAGE, conflicts: [] }
      : { valid: false, label: 'Conflict', message: conflicts[0].message, conflicts };
  }

  // ------------------------------------------------------------------ create

  async create(actor: AuthUser, dto: CreateHearingDto, meta: RequestMeta) {
    const date = requireDate(dto.date);
    const slots = buildSlots(await this.settings.schedulePolicy());
    assertBookable(date, dto.slot, slots);
    const slotInfo = slots.find((s) => s.slot === dto.slot) as Slot;
    try {
      return await this.prisma.$transaction(
        async (tx) => {
          await this.lock(tx, [date]);
          const c = await this.loadCase(tx, dto.caseId);
          if (!SCHEDULABLE.includes(c.status) || !c.courtId || !c.judgeId) {
            throw new ConflictException({
              code: 'NOT_SCHEDULABLE',
              message: 'Only allocated cases can be given a hearing.',
            });
          }
          const judgeId = dto.judgeId ?? c.judgeId;
          await this.assertTargets(tx, c, dto.courtroomId, judgeId);
          const conflicts = await this.engine.findConflicts(tx, {
            courtroomId: dto.courtroomId,
            judgeId,
            lawyerIds: c.lawyerIds,
            date,
            slot: dto.slot,
          });
          if (conflicts.length > 0) throw conflictError(conflicts);

          const created = await tx.hearing.create({
            data: {
              caseId: c.id,
              courtroomId: dto.courtroomId,
              judgeId,
              date,
              timeSlot: dto.slot,
              startTime: slotInfo.start,
              purpose: dto.purpose,
            },
            select: { id: true },
          });
          const h = await this.hearingFull(tx, created.id);
          if (c.status !== 'HEARING_FIXED') {
            await tx.case.update({ where: { id: c.id }, data: { status: 'HEARING_FIXED' } });
          }
          const when = `${ddmmyyyy(date)} at ${slotInfo.start}`;
          await tx.caseEvent.create({
            data: {
              caseId: c.id,
              type: CaseEventType.HEARING_SCHEDULED,
              description: `Hearing scheduled for ${when} in ${h.courtroom?.name ?? 'the court'} before ${fullName(h.judge)}.`,
              actorId: actor.id,
            },
          });
          await this.audit_(
            tx,
            actor,
            AuditAction.HEARING_SCHEDULED,
            'Hearing',
            h.id,
            {
              ucn: c.ucn,
              date: isoDate(date),
              slot: dto.slot,
              courtroomId: dto.courtroomId,
              judgeId,
            },
            meta,
          );
          await this.notify(
            tx,
            c.audience,
            'HEARING_SCHEDULED',
            'Hearing scheduled',
            `${c.ucn}: hearing on ${when}, ${h.courtroom?.name ?? ''}, ${fullName(h.judge)}.`,
          );
          await this.syncCauseList(tx, c.courtId, date);
          return { message: 'Hearing scheduled successfully.', hearing: hearingView(h, slots) };
        },
        { timeout: 20_000 },
      );
    } catch (error) {
      throw this.mapUnique(error);
    }
  }

  // ------------------------------------------------------------------ reschedule

  async reschedule(actor: AuthUser, id: string, dto: RescheduleDto, meta: RequestMeta) {
    const date = requireDate(dto.date);
    const slots = buildSlots(await this.settings.schedulePolicy());
    assertBookable(date, dto.slot, slots);
    const slotInfo = slots.find((s) => s.slot === dto.slot) as Slot;
    const pre = await this.prisma.hearing.findUnique({ where: { id }, select: { date: true } });
    if (!pre) throw new NotFoundException(Messages.NOT_FOUND);
    try {
      return await this.prisma.$transaction(
        async (tx) => {
          await this.lock(tx, [pre.date, date]);
          const old = await this.hearingFull(tx, id);
          if (old.status === 'CANCELLED' || old.status === 'HELD') {
            throw new ConflictException({
              code: 'NOT_RESCHEDULABLE',
              message:
                old.status === 'CANCELLED'
                  ? 'A cancelled hearing cannot be rescheduled.'
                  : 'A hearing that has already been held cannot be rescheduled.',
            });
          }
          const c = await this.loadCase(tx, old.caseId);
          const courtroomId = dto.courtroomId ?? old.courtroomId;
          const judgeId = dto.judgeId ?? old.judgeId;
          if (!courtroomId) throw bad('courtroomId', 'Choose a courtroom.');
          if (
            isoDate(old.date) === dto.date &&
            old.timeSlot === dto.slot &&
            courtroomId === old.courtroomId &&
            judgeId === old.judgeId
          ) {
            throw bad('slot', 'Choose a different date, slot, courtroom or judge.');
          }
          await this.assertTargets(tx, c, courtroomId, judgeId);
          const conflicts = await this.engine.findConflicts(tx, {
            courtroomId,
            judgeId,
            lawyerIds: c.lawyerIds,
            date,
            slot: dto.slot,
            excludeHearingId: id,
          });
          if (conflicts.length > 0) throw conflictError(conflicts);

          await tx.hearing.update({
            where: { id },
            data: {
              date,
              timeSlot: dto.slot,
              startTime: slotInfo.start,
              courtroomId,
              judgeId,
              status: 'SCHEDULED',
            },
          });
          const h = await this.hearingFull(tx, id);
          const when = `${ddmmyyyy(date)} at ${slotInfo.start}`;
          await tx.caseEvent.create({
            data: {
              caseId: c.id,
              type: CaseEventType.HEARING_RESCHEDULED,
              description: `Hearing moved from ${ddmmyyyy(old.date)} at ${old.startTime ?? ''} to ${when} in ${h.courtroom?.name ?? 'the court'} before ${fullName(h.judge)}.`,
              actorId: actor.id,
            },
          });
          await this.audit_(
            tx,
            actor,
            AuditAction.HEARING_RESCHEDULED,
            'Hearing',
            id,
            {
              ucn: c.ucn,
              from: {
                date: isoDate(old.date),
                slot: old.timeSlot,
                courtroomId: old.courtroomId,
                judgeId: old.judgeId,
              },
              to: { date: isoDate(date), slot: dto.slot, courtroomId, judgeId },
              resolveConflict: dto.resolveConflict === true,
            },
            meta,
          );
          await this.notify(
            tx,
            c.audience,
            'HEARING_RESCHEDULED',
            'Hearing rescheduled',
            `${c.ucn}: hearing moved to ${when}, ${h.courtroom?.name ?? ''}, ${fullName(h.judge)}.`,
          );
          await this.syncCauseList(tx, old.courtroom?.courtId, old.date);
          await this.syncCauseList(tx, c.courtId, date);
          return {
            message:
              dto.resolveConflict === true
                ? 'Schedule overlap resolved manually.'
                : 'Hearing rescheduled successfully.',
            hearing: hearingView(h, slots),
          };
        },
        { timeout: 20_000 },
      );
    } catch (error) {
      throw this.mapUnique(error);
    }
  }

  // ------------------------------------------------------------------ cancel

  async cancel(actor: AuthUser, id: string, dto: CancelHearingDto, meta: RequestMeta) {
    const pre = await this.prisma.hearing.findUnique({ where: { id }, select: { date: true } });
    if (!pre) throw new NotFoundException(Messages.NOT_FOUND);
    const slots = buildSlots(await this.settings.schedulePolicy());
    return this.prisma.$transaction(
      async (tx) => {
        await this.lock(tx, [pre.date]);
        const h0 = await this.hearingFull(tx, id);
        if (h0.status === 'CANCELLED' || h0.status === 'HELD') {
          throw new ConflictException({
            code: 'NOT_CANCELLABLE',
            message:
              h0.status === 'CANCELLED'
                ? 'This hearing is already cancelled.'
                : 'A hearing that has already been held cannot be cancelled.',
          });
        }
        const c = await this.loadCase(tx, h0.caseId);
        await tx.hearing.update({ where: { id }, data: { status: 'CANCELLED' } });
        const others = await tx.hearing.count({
          where: {
            caseId: c.id,
            id: { not: id },
            status: { in: ['SCHEDULED', 'ADJOURNED'] },
            date: { gte: todayUtc() },
          },
        });
        if (others === 0 && c.status === 'HEARING_FIXED') {
          await tx.case.update({ where: { id: c.id }, data: { status: 'ALLOCATED' } });
        }
        const when = `${ddmmyyyy(h0.date)} at ${h0.startTime ?? ''}`;
        await tx.caseEvent.create({
          data: {
            caseId: c.id,
            type: CaseEventType.HEARING_CANCELLED,
            description: `Hearing of ${when} cancelled. Reason: ${dto.reason}`,
            actorId: actor.id,
          },
        });
        await this.audit_(
          tx,
          actor,
          AuditAction.HEARING_CANCELLED,
          'Hearing',
          id,
          {
            ucn: c.ucn,
            date: isoDate(h0.date),
            slot: h0.timeSlot,
            reason: dto.reason,
          },
          meta,
        );
        await this.notify(
          tx,
          c.audience,
          'HEARING_CANCELLED',
          'Hearing cancelled',
          `${c.ucn}: the hearing of ${when} was cancelled. Reason: ${dto.reason}`,
        );
        await this.syncCauseList(tx, h0.courtroom?.courtId, h0.date);
        const h = await this.hearingFull(tx, id);
        return { message: 'Hearing cancelled.', hearing: hearingView(h, slots) };
      },
      { timeout: 20_000 },
    );
  }

  // ------------------------------------------------------------------ board

  /** UC-3.1: Master Bench Allocation and Scheduling Board for one court and day. */
  async board(courtId: string, dateStr: string) {
    const date = requireDate(dateStr);
    const court = await this.prisma.court.findUnique({ where: { id: courtId } });
    if (!court) throw new NotFoundException(Messages.NOT_FOUND);
    const policy = await this.settings.schedulePolicy();
    const slots = buildSlots(policy);
    const working = isWorkingDay(date);
    const [rooms, judges, scan, list] = await Promise.all([
      this.prisma.courtroom.findMany({
        where: { courtId, isActive: true },
        orderBy: [{ benchNo: 'asc' }, { name: 'asc' }],
      }),
      this.prisma.user.findMany({
        where: { role: 'JUDGE', status: 'ACTIVE', courtId },
        select: { id: true, firstName: true, lastName: true, courtroomId: true },
      }),
      this.engine.scan(this.prisma, date),
      this.prisma.causeList.findUnique({ where: { courtId_date: { courtId, date } } }),
    ]);
    const roomIds = new Set(rooms.map((r) => r.id));
    const courtHearings = scan.hearings.filter((h) => h.courtroomId && roomIds.has(h.courtroomId));
    const usedByJudge = new Map<string, number>();
    for (const h of scan.hearings)
      usedByJudge.set(h.judgeId, (usedByJudge.get(h.judgeId) ?? 0) + 1);

    const courtrooms = rooms.map((room) => {
      const inRoom = courtHearings.filter((h) => h.courtroomId === room.id);
      const judgeMap = new Map<string, { id: string; name: string }>();
      for (const j of judges.filter((j) => j.courtroomId === room.id)) {
        judgeMap.set(j.id, { id: j.id, name: fullName(j) });
      }
      for (const h of inRoom) judgeMap.set(h.judge.id, { id: h.judge.id, name: fullName(h.judge) });
      return {
        id: room.id,
        name: room.name,
        benchNo: room.benchNo,
        judges: [...judgeMap.values()].map((j) => ({
          ...j,
          used: usedByJudge.get(j.id) ?? 0,
          total: working ? slots.length : 0,
        })),
        cells: slots.map((s) => {
          const h = inRoom.find((x) => x.timeSlot === s.slot);
          return {
            slot: s.slot,
            hearing: h ? hearingView(h, slots, scan.conflicts.get(h.id) ?? []) : null,
          };
        }),
      };
    });
    const conflictCount = courtHearings.filter((h) => scan.conflicts.has(h.id)).length;
    return {
      court: { id: court.id, name: court.name },
      date: dateStr,
      weekday: weekdayOf(date),
      isWorkingDay: working,
      policy,
      slots,
      courtrooms,
      hearingCount: courtHearings.length,
      conflictCount,
      causeList: list ? { status: list.status, publishedAt: list.publishedAt } : null,
    };
  }

  async week(courtId: string, weekStartStr: string) {
    const monday = mondayOf(requireDate(weekStartStr, 'weekStart'));
    const rooms = await this.prisma.courtroom.findMany({
      where: { courtId, isActive: true },
      orderBy: [{ benchNo: 'asc' }, { name: 'asc' }],
      select: { id: true, name: true },
    });
    const days = Array.from({ length: 5 }, (_, i) => addDays(monday, i));
    const perDay = [];
    for (const d of days) {
      const scan = await this.engine.scan(this.prisma, d);
      const mine = scan.hearings.filter((h) => h.courtroom?.courtId === courtId);
      perDay.push({
        date: isoDate(d),
        counts: Object.fromEntries(
          rooms.map((r) => [r.id, mine.filter((h) => h.courtroomId === r.id).length]),
        ),
        total: mine.length,
        conflicts: mine.filter((h) => scan.conflicts.has(h.id)).length,
      });
    }
    return { courtId, weekStart: isoDate(monday), courtrooms: rooms, days: perDay };
  }

  /** UC-3.2: scan one court and date and list every hearing in conflict. */
  async runCheck(courtId: string, dateStr: string) {
    const date = requireDate(dateStr);
    const slots = buildSlots(await this.settings.schedulePolicy());
    const scan = await this.engine.scan(this.prisma, date);
    const conflicting = scan.hearings
      .filter((h) => h.courtroom?.courtId === courtId && scan.conflicts.has(h.id))
      .map((h) => hearingView(h, slots, scan.conflicts.get(h.id)));
    return conflicting.length === 0
      ? { valid: true, message: CLEAR_MESSAGE, conflicts: [] }
      : {
          valid: false,
          message: conflicting[0].conflicts[0].message,
          conflicts: conflicting,
        };
  }

  async availableSlots(q: {
    caseId: string;
    from?: string;
    days: number;
    excludeHearingId?: string;
  }) {
    const c = await this.loadCase(this.prisma, q.caseId);
    if (!c.courtId || !c.judgeId) throw bad('caseId', 'This case has no court and judge yet.');
    const slots = buildSlots(await this.settings.schedulePolicy());
    const from = q.from ? requireDate(q.from, 'from') : todayUtc();
    const start = from.getTime() < todayUtc().getTime() ? todayUtc() : from;
    return {
      caseId: c.id,
      days: await this.engine.availableSlots(this.prisma, {
        courtId: c.courtId,
        judgeId: c.judgeId,
        lawyerIds: c.lawyerIds,
        from: start,
        days: q.days,
        slots,
        excludeHearingId: q.excludeHearingId,
      }),
    };
  }

  /** Allocated cases of a court for the "Schedule hearing" and auto-generate dialogs, unscheduled first. */
  async schedulableCases(courtId: string, search?: string) {
    const rows = await this.prisma.case.findMany({
      where: {
        courtId,
        status: { in: SCHEDULABLE },
        judgeId: { not: null },
        ...(search
          ? {
              OR: [
                { ucn: { contains: search, mode: 'insensitive' } },
                { title: { contains: search, mode: 'insensitive' } },
              ],
            }
          : {}),
      },
      select: {
        id: true,
        ucn: true,
        title: true,
        caseType: true,
        judgeId: true,
        judge: { select: { firstName: true, lastName: true } },
        _count: {
          select: {
            hearings: {
              where: { status: { in: ['SCHEDULED', 'ADJOURNED'] }, date: { gte: todayUtc() } },
            },
          },
        },
      },
      orderBy: [{ filingDate: 'asc' }, { id: 'asc' }],
      take: 100,
    });
    return rows
      .map((c) => ({
        id: c.id,
        ucn: c.ucn,
        title: c.title,
        caseType: c.caseType,
        judgeId: c.judgeId,
        judge: c.judge ? fullName(c.judge) : null,
        hasUpcomingHearing: c._count.hearings > 0,
      }))
      .sort((a, b) => Number(a.hasUpcomingHearing) - Number(b.hasUpcomingHearing));
  }

  // ------------------------------------------------------------------ auto-generate

  /** The "automated cause list scheduling matrix": first-fit placement of cases into free slots of one day. */
  async autoGenerate(actor: AuthUser, dto: AutoGenerateDto, meta: RequestMeta) {
    const date = requireDate(dto.date);
    const slots = buildSlots(await this.settings.schedulePolicy());
    if (!isWorkingDay(date)) throw bad('date', 'Hearings can only be scheduled Monday to Friday.');
    assertBookable(date, slots[0]?.slot ?? 1, slots);
    try {
      return await this.prisma.$transaction(
        async (tx) => {
          await this.lock(tx, [date]);
          const rooms = await tx.courtroom.findMany({
            where: { courtId: dto.courtId, isActive: true },
            orderBy: [{ benchNo: 'asc' }, { name: 'asc' }],
            select: { id: true, name: true },
          });
          const judgeRooms = new Map(
            (
              await tx.user.findMany({
                where: { role: 'JUDGE', courtId: dto.courtId },
                select: { id: true, courtroomId: true },
              })
            ).map((j) => [j.id, j.courtroomId]),
          );
          const placed: ReturnType<typeof hearingView>[] = [];
          const unplaced: { caseId: string; ucn: string | null; reason: string }[] = [];

          for (const caseId of [...new Set(dto.caseIds)]) {
            const c = await tx.case.findUnique({
              where: { id: caseId },
              select: { id: true, ucn: true, status: true, courtId: true, judgeId: true },
            });
            if (!c) {
              unplaced.push({ caseId, ucn: null, reason: 'Case not found.' });
              continue;
            }
            if (c.courtId !== dto.courtId || !c.judgeId || !SCHEDULABLE.includes(c.status)) {
              unplaced.push({ caseId, ucn: c.ucn, reason: 'Not an allocated case of this court.' });
              continue;
            }
            const upcoming = await tx.hearing.count({
              where: {
                caseId,
                status: { in: ['SCHEDULED', 'ADJOURNED'] },
                date: { gte: todayUtc() },
              },
            });
            if (upcoming > 0) {
              unplaced.push({ caseId, ucn: c.ucn, reason: 'Already has an upcoming hearing.' });
              continue;
            }
            const ctx = await this.loadCase(tx, caseId);
            const preferred = judgeRooms.get(c.judgeId);
            const order = [...rooms].sort(
              (a, b) => Number(b.id === preferred) - Number(a.id === preferred),
            );
            let done = false;
            for (const s of slots) {
              for (const room of order) {
                const conflicts = await this.engine.findConflicts(tx, {
                  courtroomId: room.id,
                  judgeId: c.judgeId,
                  lawyerIds: ctx.lawyerIds,
                  date,
                  slot: s.slot,
                });
                if (conflicts.length > 0) continue;
                const created = await tx.hearing.create({
                  data: {
                    caseId,
                    courtroomId: room.id,
                    judgeId: c.judgeId,
                    date,
                    timeSlot: s.slot,
                    startTime: s.start,
                  },
                  select: { id: true },
                });
                await tx.case.update({ where: { id: caseId }, data: { status: 'HEARING_FIXED' } });
                await tx.caseEvent.create({
                  data: {
                    caseId,
                    type: CaseEventType.HEARING_SCHEDULED,
                    description: `Hearing scheduled for ${ddmmyyyy(date)} at ${s.start} in ${room.name}.`,
                    actorId: actor.id,
                  },
                });
                await this.notify(
                  tx,
                  ctx.audience,
                  'HEARING_SCHEDULED',
                  'Hearing scheduled',
                  `${c.ucn}: hearing on ${ddmmyyyy(date)} at ${s.start}, ${room.name}.`,
                );
                placed.push(hearingView(await this.hearingFull(tx, created.id), slots));
                done = true;
                break;
              }
              if (done) break;
            }
            if (!done) {
              unplaced.push({
                caseId,
                ucn: c.ucn,
                reason: 'No free slot where the judge, a courtroom and all lawyers are available.',
              });
            }
          }
          await this.audit_(
            tx,
            actor,
            AuditAction.SCHEDULE_AUTO_GENERATED,
            'Court',
            dto.courtId,
            {
              date: isoDate(date),
              placed: placed.length,
              unplaced: unplaced.length,
            },
            meta,
          );
          await this.syncCauseList(tx, dto.courtId, date);
          return { placed, unplaced, message: `${placed.length} hearing(s) scheduled.` };
        },
        { timeout: 60_000 },
      );
    } catch (error) {
      throw this.mapUnique(error);
    }
  }

  // ------------------------------------------------------------------ cause lists

  async publish(actor: AuthUser, dto: PublishDto, meta: RequestMeta) {
    const date = requireDate(dto.date);
    const slots = buildSlots(await this.settings.schedulePolicy());
    return this.prisma.$transaction(
      async (tx) => {
        await this.lock(tx, [date]);
        const scan = await this.engine.scan(tx, date);
        const mine = scan.hearings.filter((h) => h.courtroom?.courtId === dto.courtId);
        const clashing = mine.filter((h) => scan.conflicts.has(h.id));
        if (clashing.length > 0) {
          throw new ConflictException({
            code: 'CONFLICTS_PRESENT',
            message: PUBLISH_BLOCKED_MESSAGE,
            details: clashing.flatMap((h) => scan.conflicts.get(h.id) ?? []),
          });
        }
        const existing = await tx.causeList.findUnique({
          where: { courtId_date: { courtId: dto.courtId, date } },
        });
        const first = !existing || existing.status !== 'PUBLISHED';
        const list = existing
          ? await tx.causeList.update({
              where: { id: existing.id },
              data: { status: 'PUBLISHED', publishedAt: first ? new Date() : existing.publishedAt },
            })
          : await tx.causeList.create({
              data: {
                courtId: dto.courtId,
                date,
                status: 'PUBLISHED',
                publishedAt: new Date(),
                createdById: actor.id,
              },
            });
        const count = await this.rebuildEntries(tx, list.id, dto.courtId, date);
        if (first) {
          const people = new Map<string, string[]>();
          for (const h of mine) {
            const users = new Set([
              h.case.filedById,
              ...h.case.parties.flatMap((p) => (p.lawyer ? [p.lawyer.userId] : [])),
              h.judgeId,
            ]);
            for (const u of users) {
              people.set(u, [...(people.get(u) ?? []), `${h.case.ucn} at ${h.startTime ?? ''}`]);
            }
          }
          const now = new Date();
          await tx.notification.createMany({
            data: [...people].map(([userId, items]) => ({
              userId,
              type: 'CAUSE_LIST_PUBLISHED',
              title: 'Cause list published',
              body: `The cause list for ${ddmmyyyy(date)} is published. Listed: ${items.join('; ')}.`,
              sentAt: now,
            })),
          });
        }
        await this.audit_(
          tx,
          actor,
          AuditAction.CAUSE_LIST_PUBLISHED,
          'CauseList',
          list.id,
          {
            courtId: dto.courtId,
            date: isoDate(date),
            entries: count,
          },
          meta,
        );
        return {
          message: 'Cause list published.',
          causeList: {
            id: list.id,
            status: list.status,
            publishedAt: list.publishedAt,
            entries: count,
          },
          slots: slots.length,
        };
      },
      { timeout: 30_000 },
    );
  }

  async adminCauseList(courtId: string, dateStr: string) {
    const date = requireDate(dateStr);
    const list = await this.prisma.causeList.findUnique({
      where: { courtId_date: { courtId, date } },
      include: {
        entries: {
          orderBy: { serialNo: 'asc' },
          include: { hearing: { include: scanInclude } },
        },
      },
    });
    if (!list) return { status: null, date: dateStr, entries: [] };
    const slots = buildSlots(await this.settings.schedulePolicy());
    return {
      id: list.id,
      status: list.status,
      date: dateStr,
      publishedAt: list.publishedAt,
      entries: list.entries.map((e) => ({
        serialNo: e.serialNo,
        ...hearingView(e.hearing, slots),
      })),
    };
  }
}
