import { Type } from 'class-transformer';
import {
  ArrayMaxSize,
  ArrayMinSize,
  IsArray,
  IsBoolean,
  IsIn,
  IsInt,
  IsNotEmpty,
  IsOptional,
  IsString,
  IsUUID,
  Matches,
  Max,
  MaxLength,
  Min,
} from 'class-validator';
import { PageQueryDto } from '../common/pagination';
import { Trim, TrimOrUndefined } from '../common/validators';

const DATE = /^\d{4}-\d{2}-\d{2}$/;
const DATE_MESSAGE = 'Enter a valid date (YYYY-MM-DD).';

export class CheckDto {
  @IsUUID()
  caseId: string;

  @IsUUID()
  courtroomId: string;

  @IsOptional()
  @IsUUID()
  judgeId?: string;

  @Matches(DATE, { message: DATE_MESSAGE })
  date: string;

  @Type(() => Number)
  @IsInt()
  @Min(1)
  @Max(48)
  slot: number;

  /** Set when checking a move of an existing hearing: that hearing is ignored. */
  @IsOptional()
  @IsUUID()
  hearingId?: string;
}

export class CreateHearingDto {
  @IsUUID()
  caseId: string;

  @IsUUID()
  courtroomId: string;

  @IsOptional()
  @IsUUID()
  judgeId?: string;

  @Matches(DATE, { message: DATE_MESSAGE })
  date: string;

  @Type(() => Number)
  @IsInt()
  @Min(1)
  @Max(48)
  slot: number;

  @TrimOrUndefined()
  @IsOptional()
  @IsString()
  @MaxLength(200)
  purpose?: string;
}

export class RescheduleDto {
  @Matches(DATE, { message: DATE_MESSAGE })
  date: string;

  @Type(() => Number)
  @IsInt()
  @Min(1)
  @Max(48)
  slot: number;

  @IsOptional()
  @IsUUID()
  courtroomId?: string;

  @IsOptional()
  @IsUUID()
  judgeId?: string;

  @IsOptional()
  @IsBoolean()
  resolveConflict?: boolean;
}

export class CancelHearingDto {
  @Trim()
  @IsNotEmpty({ message: 'Please enter a reason for cancelling.' })
  @IsString()
  @MaxLength(500)
  reason: string;
}

export class BoardQueryDto {
  @IsUUID()
  courtId: string;

  @Matches(DATE, { message: DATE_MESSAGE })
  date: string;
}

export class WeekQueryDto {
  @IsUUID()
  courtId: string;

  @Matches(DATE, { message: DATE_MESSAGE })
  weekStart: string;
}

export class RunCheckDto {
  @IsUUID()
  courtId: string;

  @Matches(DATE, { message: DATE_MESSAGE })
  date: string;
}

export class AvailableSlotsQueryDto {
  @IsUUID()
  caseId: string;

  @IsOptional()
  @Matches(DATE, { message: DATE_MESSAGE })
  from?: string;

  @IsOptional()
  @Type(() => Number)
  @IsInt()
  @Min(1)
  @Max(31)
  days: number = 14;

  /** The hearing being moved: its own slot counts as free. */
  @IsOptional()
  @IsUUID()
  excludeHearingId?: string;
}

export class AutoGenerateDto {
  @IsUUID()
  courtId: string;

  @Matches(DATE, { message: DATE_MESSAGE })
  date: string;

  @IsArray()
  @ArrayMinSize(1, { message: 'Choose at least one case.' })
  @ArrayMaxSize(100)
  @IsUUID('all', { each: true })
  caseIds: string[];
}

export class PublishDto {
  @IsUUID()
  courtId: string;

  @Matches(DATE, { message: DATE_MESSAGE })
  date: string;
}

export class AdminCauseListQueryDto {
  @IsUUID()
  courtId: string;

  @Matches(DATE, { message: DATE_MESSAGE })
  date: string;
}

export class SchedulableCasesQueryDto {
  @IsUUID()
  courtId: string;

  @TrimOrUndefined()
  @IsOptional()
  @IsString()
  @MaxLength(100)
  search?: string;
}

export class CauseListQueryDto {
  @IsOptional()
  @Matches(DATE, { message: DATE_MESSAGE })
  date?: string;

  @IsOptional()
  @IsUUID()
  courtroomId?: string;

  @IsOptional()
  @IsUUID()
  courtId?: string;
}

export class MyHearingsQueryDto extends PageQueryDto {
  @IsOptional()
  @IsIn(['upcoming', 'past'])
  when: 'upcoming' | 'past' = 'upcoming';
}

export class JudgeHearingsQueryDto {
  @IsOptional()
  @Matches(DATE, { message: DATE_MESSAGE })
  from?: string;

  @IsOptional()
  @Matches(DATE, { message: DATE_MESSAGE })
  to?: string;
}
