import {
  Body,
  Controller,
  Get,
  HttpCode,
  HttpStatus,
  Param,
  Patch,
  Post,
  Query,
  Req,
} from '@nestjs/common';
import { ApiBearerAuth, ApiCookieAuth, ApiTags } from '@nestjs/swagger';
import type { Request } from 'express';
import { RequestMeta } from '../admin/constants';
import { AuthUser, CurrentUser, Roles } from '../common/decorators';
import { ParseIdPipe } from '../common/parse-id.pipe';
import { HearingsService } from './hearings.service';
import {
  AdminCauseListQueryDto,
  AutoGenerateDto,
  AvailableSlotsQueryDto,
  BoardQueryDto,
  CancelHearingDto,
  CauseListQueryDto,
  CheckDto,
  CreateHearingDto,
  JudgeHearingsQueryDto,
  MyHearingsQueryDto,
  PublishDto,
  RescheduleDto,
  RunCheckDto,
  SchedulableCasesQueryDto,
  WeekQueryDto,
} from './scheduling.dto';
import { SchedulingService } from './scheduling.service';

const meta = (req: Request): RequestMeta => ({ ip: req.ip, userAgent: req.headers['user-agent'] });

/** UC-3.1 to UC-3.3: ADMIN only. */
@ApiTags('scheduling')
@ApiCookieAuth()
@ApiBearerAuth()
@Roles('ADMIN')
@Controller('admin')
export class AdminSchedulingController {
  constructor(private readonly scheduling: SchedulingService) {}

  @HttpCode(HttpStatus.OK)
  @Post('scheduling/check')
  check(@Body() dto: CheckDto) {
    return this.scheduling.check(dto);
  }

  @Get('scheduling/board')
  board(@Query() q: BoardQueryDto) {
    return this.scheduling.board(q.courtId, q.date);
  }

  @Get('scheduling/week')
  week(@Query() q: WeekQueryDto) {
    return this.scheduling.week(q.courtId, q.weekStart);
  }

  @HttpCode(HttpStatus.OK)
  @Post('scheduling/run-check')
  runCheck(@Body() dto: RunCheckDto) {
    return this.scheduling.runCheck(dto.courtId, dto.date);
  }

  @Get('scheduling/available-slots')
  available(@Query() q: AvailableSlotsQueryDto) {
    return this.scheduling.availableSlots(q);
  }

  @Get('scheduling/schedulable-cases')
  schedulable(@Query() q: SchedulableCasesQueryDto) {
    return this.scheduling.schedulableCases(q.courtId, q.search);
  }

  @Post('scheduling/auto-generate')
  autoGenerate(@CurrentUser() user: AuthUser, @Body() dto: AutoGenerateDto, @Req() req: Request) {
    return this.scheduling.autoGenerate(user, dto, meta(req));
  }

  @Post('hearings')
  create(@CurrentUser() user: AuthUser, @Body() dto: CreateHearingDto, @Req() req: Request) {
    return this.scheduling.create(user, dto, meta(req));
  }

  @Patch('hearings/:id/reschedule')
  reschedule(
    @CurrentUser() user: AuthUser,
    @Param('id', ParseIdPipe) id: string,
    @Body() dto: RescheduleDto,
    @Req() req: Request,
  ) {
    return this.scheduling.reschedule(user, id, dto, meta(req));
  }

  @HttpCode(HttpStatus.OK)
  @Post('hearings/:id/cancel')
  cancel(
    @CurrentUser() user: AuthUser,
    @Param('id', ParseIdPipe) id: string,
    @Body() dto: CancelHearingDto,
    @Req() req: Request,
  ) {
    return this.scheduling.cancel(user, id, dto, meta(req));
  }

  @HttpCode(HttpStatus.OK)
  @Post('cause-lists/publish')
  publish(@CurrentUser() user: AuthUser, @Body() dto: PublishDto, @Req() req: Request) {
    return this.scheduling.publish(user, dto, meta(req));
  }

  @Get('cause-lists')
  causeList(@Query() q: AdminCauseListQueryDto) {
    return this.scheduling.adminCauseList(q.courtId, q.date);
  }
}

/** Read side for every signed-in user. */
@ApiTags('hearings')
@ApiCookieAuth()
@ApiBearerAuth()
@Controller()
export class HearingsController {
  constructor(private readonly hearings: HearingsService) {}

  /** Published daily cause lists; "Roster details not yet published. Check back later." when none. */
  @Get('cause-lists')
  causeLists(@CurrentUser() user: AuthUser, @Query() q: CauseListQueryDto) {
    return this.hearings.causeLists(user, q);
  }

  @Roles('LITIGANT', 'LAWYER')
  @Get('hearings/mine')
  mine(@CurrentUser() user: AuthUser, @Query() q: MyHearingsQueryDto) {
    return this.hearings.mine(user, q);
  }

  @Roles('JUDGE')
  @Get('judge/hearings')
  judge(@CurrentUser() user: AuthUser, @Query() q: JudgeHearingsQueryDto) {
    return this.hearings.judge(user, q);
  }
}
